/// <reference path="Admin/BatchAdminRequest.d.ts" />
/// <reference path="Admin/CancelBulkJobAdminRequest.d.ts" />
/// <reference path="Admin/ListBulkJobsAdminRequest.d.ts" />
/// <reference path="Admin/RevokePurchaseGoodsRequest.d.ts" />
/// <reference path="Admin/ScheduleBulkJobAdminRequest.d.ts" />
/// <reference path="Analytics/AnalyticsRequest.d.ts" />
/// <reference path="Analytics/EndSessionRequest.d.ts" />
/// <reference path="Authentication/AmazonConnectRequest.d.ts" />
/// <reference path="Authentication/AuthenticationRequest.d.ts" />
/// <reference path="Authentication/DeviceAuthenticationRequest.d.ts" />
/// <reference path="Authentication/FacebookConnectRequest.d.ts" />
/// <reference path="Authentication/GameCenterConnectRequest.d.ts" />
/// <reference path="Authentication/GooglePlayConnectRequest.d.ts" />
/// <reference path="Authentication/GooglePlusConnectRequest.d.ts" />
/// <reference path="Authentication/KongregateConnectRequest.d.ts" />
/// <reference path="Authentication/NXConnectRequest.d.ts" />
/// <reference path="Authentication/PSNAccountConnectRequest.d.ts" />
/// <reference path="Authentication/PSNConnectRequest.d.ts" />
/// <reference path="Authentication/QQConnectRequest.d.ts" />
/// <reference path="Authentication/RegistrationRequest.d.ts" />
/// <reference path="Authentication/SteamConnectRequest.d.ts" />
/// <reference path="Authentication/TwitchConnectRequest.d.ts" />
/// <reference path="Authentication/TwitterConnectRequest.d.ts" />
/// <reference path="Authentication/ViberConnectRequest.d.ts" />
/// <reference path="Authentication/WeChatConnectRequest.d.ts" />
/// <reference path="Authentication/XBOXLiveConnectRequest.d.ts" />
/// <reference path="Authentication/XboxOneConnectRequest.d.ts" />
/// <reference path="Data Types/Achievement.d.ts" />
/// <reference path="Data Types/Boughtitem.d.ts" />
/// <reference path="Data Types/BulkJob.d.ts" />
/// <reference path="Data Types/BundledGood.d.ts" />
/// <reference path="Data Types/Challenge.d.ts" />
/// <reference path="Data Types/ChallengeType.d.ts" />
/// <reference path="Data Types/ChatMessage.d.ts" />
/// <reference path="Data Types/InvitableFriend.d.ts" />
/// <reference path="Data Types/Leaderboard.d.ts" />
/// <reference path="Data Types/LeaderboardData.d.ts" />
/// <reference path="Data Types/LeaderboardRankDetails.d.ts" />
/// <reference path="Data Types/Location.d.ts" />
/// <reference path="Data Types/MatchedPlayer.d.ts" />
/// <reference path="Data Types/Participant.d.ts" />
/// <reference path="Data Types/PendingMatch.d.ts" />
/// <reference path="Data Types/Player.d.ts" />
/// <reference path="Data Types/PlayerDetail.d.ts" />
/// <reference path="Data Types/PlayerMessage.d.ts" />
/// <reference path="Data Types/PlayerTransaction.d.ts" />
/// <reference path="Data Types/PlayerTransactionItem.d.ts" />
/// <reference path="Data Types/PlayerTurnCount.d.ts" />
/// <reference path="Data Types/SocialStatus.d.ts" />
/// <reference path="Data Types/Team.d.ts" />
/// <reference path="Data Types/UploadData.d.ts" />
/// <reference path="Data Types/VirtualGood.d.ts" />
/// <reference path="Leaderboards/AroundMeLeaderboardRequest.d.ts" />
/// <reference path="Leaderboards/GetLeaderboardEntriesRequest.d.ts" />
/// <reference path="Leaderboards/LeaderboardDataRequest.d.ts" />
/// <reference path="Leaderboards/LeaderboardsEntriesRequest.d.ts" />
/// <reference path="Leaderboards/ListLeaderboardsRequest.d.ts" />
/// <reference path="Leaderboards/SocialLeaderboardDataRequest.d.ts" />
/// <reference path="Misc/GetDownloadableRequest.d.ts" />
/// <reference path="Misc/GetPropertyRequest.d.ts" />
/// <reference path="Misc/GetPropertySetRequest.d.ts" />
/// <reference path="Misc/GetUploadedRequest.d.ts" />
/// <reference path="Misc/GetUploadUrlRequest.d.ts" />
/// <reference path="Misc/PushRegistrationRequest.d.ts" />
/// <reference path="Misc/SocialStatusRequest.d.ts" />
/// <reference path="Multiplayer/AcceptChallengeRequest.d.ts" />
/// <reference path="Multiplayer/ChatOnChallengeRequest.d.ts" />
/// <reference path="Multiplayer/CreateChallengeRequest.d.ts" />
/// <reference path="Multiplayer/DeclineChallengeRequest.d.ts" />
/// <reference path="Multiplayer/FindChallengeRequest.d.ts" />
/// <reference path="Multiplayer/FindMatchRequest.d.ts" />
/// <reference path="Multiplayer/FindPendingMatchesRequest.d.ts" />
/// <reference path="Multiplayer/GetChallengeRequest.d.ts" />
/// <reference path="Multiplayer/JoinChallengeRequest.d.ts" />
/// <reference path="Multiplayer/JoinPendingMatchRequest.d.ts" />
/// <reference path="Multiplayer/ListChallengeRequest.d.ts" />
/// <reference path="Multiplayer/ListChallengeTypeRequest.d.ts" />
/// <reference path="Multiplayer/LogChallengeEventRequest.d.ts" />
/// <reference path="Multiplayer/MatchDetailsRequest.d.ts" />
/// <reference path="Multiplayer/MatchmakingRequest.d.ts" />
/// <reference path="Multiplayer/WithdrawChallengeRequest.d.ts" />
/// <reference path="Player Operations/AccountDetailsRequest.d.ts" />
/// <reference path="Player Operations/ChangeUserDetailsRequest.d.ts" />
/// <reference path="Player Operations/DismissMessageRequest.d.ts" />
/// <reference path="Player Operations/DismissMultipleMessagesRequest.d.ts" />
/// <reference path="Player Operations/GetMessageRequest.d.ts" />
/// <reference path="Player Operations/ListAchievementsRequest.d.ts" />
/// <reference path="Player Operations/ListGameFriendsRequest.d.ts" />
/// <reference path="Player Operations/ListInviteFriendsRequest.d.ts" />
/// <reference path="Player Operations/ListMessageDetailRequest.d.ts" />
/// <reference path="Player Operations/ListMessageRequest.d.ts" />
/// <reference path="Player Operations/ListMessageSummaryRequest.d.ts" />
/// <reference path="Player Operations/ListTransactionsRequest.d.ts" />
/// <reference path="Player Operations/LogEventRequest.d.ts" />
/// <reference path="Player Operations/SendFriendMessageRequest.d.ts" />
/// <reference path="Player Operations/SocialDisconnectRequest.d.ts" />
/// <reference path="Player Operations/UpdateMessageRequest.d.ts" />
/// <reference path="Store/AmazonBuyGoodsRequest.d.ts" />
/// <reference path="Store/BuyVirtualGoodsRequest.d.ts" />
/// <reference path="Store/ConsumeVirtualGoodRequest.d.ts" />
/// <reference path="Store/GooglePlayBuyGoodsRequest.d.ts" />
/// <reference path="Store/IOSBuyGoodsRequest.d.ts" />
/// <reference path="Store/ListVirtualGoodsRequest.d.ts" />
/// <reference path="Store/PsnBuyGoodsRequest.d.ts" />
/// <reference path="Store/SteamBuyGoodsRequest.d.ts" />
/// <reference path="Store/WindowsBuyGoodsRequest.d.ts" />
/// <reference path="Teams/CreateTeamRequest.d.ts" />
/// <reference path="Teams/DropTeamRequest.d.ts" />
/// <reference path="Teams/GetMyTeamsRequest.d.ts" />
/// <reference path="Teams/GetTeamRequest.d.ts" />
/// <reference path="Teams/JoinTeamRequest.d.ts" />
/// <reference path="Teams/LeaveTeamRequest.d.ts" />
/// <reference path="Teams/ListTeamChatRequest.d.ts" />
/// <reference path="Teams/ListTeamsRequest.d.ts" />
/// <reference path="Teams/SendTeamChatMessageRequest.d.ts" />
