/// <reference path="./typings/Admin/BatchAdminRequest.d.ts" />
/// <reference path="./typings/Admin/CancelBulkJobAdminRequest.d.ts" />
/// <reference path="./typings/Admin/ListBulkJobsAdminRequest.d.ts" />
/// <reference path="./typings/Admin/RevokePurchaseGoodsRequest.d.ts" />
/// <reference path="./typings/Admin/ScheduleBulkJobAdminRequest.d.ts" />
/// <reference path="./typings/Analytics/AnalyticsRequest.d.ts" />
/// <reference path="./typings/Analytics/EndSessionRequest.d.ts" />
/// <reference path="./typings/Authentication/AmazonConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/AuthenticationRequest.d.ts" />
/// <reference path="./typings/Authentication/DeviceAuthenticationRequest.d.ts" />
/// <reference path="./typings/Authentication/FacebookConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/GameCenterConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/GooglePlayConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/GooglePlusConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/KongregateConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/NXConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/PSNAccountConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/PSNConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/QQConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/RegistrationRequest.d.ts" />
/// <reference path="./typings/Authentication/SteamConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/TwitchConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/TwitterConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/ViberConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/WeChatConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/XBOXLiveConnectRequest.d.ts" />
/// <reference path="./typings/Authentication/XboxOneConnectRequest.d.ts" />
/// <reference path="./typings/Data Types/Achievement.d.ts" />
/// <reference path="./typings/Data Types/Boughtitem.d.ts" />
/// <reference path="./typings/Data Types/BulkJob.d.ts" />
/// <reference path="./typings/Data Types/BundledGood.d.ts" />
/// <reference path="./typings/Data Types/Challenge.d.ts" />
/// <reference path="./typings/Data Types/ChallengeType.d.ts" />
/// <reference path="./typings/Data Types/ChatMessage.d.ts" />
/// <reference path="./typings/Data Types/InvitableFriend.d.ts" />
/// <reference path="./typings/Data Types/Leaderboard.d.ts" />
/// <reference path="./typings/Data Types/LeaderboardData.d.ts" />
/// <reference path="./typings/Data Types/LeaderboardRankDetails.d.ts" />
/// <reference path="./typings/Data Types/Location.d.ts" />
/// <reference path="./typings/Data Types/MatchedPlayer.d.ts" />
/// <reference path="./typings/Data Types/Participant.d.ts" />
/// <reference path="./typings/Data Types/PendingMatch.d.ts" />
/// <reference path="./typings/Data Types/Player.d.ts" />
/// <reference path="./typings/Data Types/PlayerDetail.d.ts" />
/// <reference path="./typings/Data Types/PlayerMessage.d.ts" />
/// <reference path="./typings/Data Types/PlayerTransaction.d.ts" />
/// <reference path="./typings/Data Types/PlayerTransactionItem.d.ts" />
/// <reference path="./typings/Data Types/PlayerTurnCount.d.ts" />
/// <reference path="./typings/Data Types/SocialStatus.d.ts" />
/// <reference path="./typings/Data Types/Team.d.ts" />
/// <reference path="./typings/Data Types/UploadData.d.ts" />
/// <reference path="./typings/Data Types/VirtualGood.d.ts" />
/// <reference path="./typings/Leaderboards/AroundMeLeaderboardRequest.d.ts" />
/// <reference path="./typings/Leaderboards/GetLeaderboardEntriesRequest.d.ts" />
/// <reference path="./typings/Leaderboards/LeaderboardDataRequest.d.ts" />
/// <reference path="./typings/Leaderboards/LeaderboardsEntriesRequest.d.ts" />
/// <reference path="./typings/Leaderboards/ListLeaderboardsRequest.d.ts" />
/// <reference path="./typings/Leaderboards/SocialLeaderboardDataRequest.d.ts" />
/// <reference path="./typings/Misc/GetDownloadableRequest.d.ts" />
/// <reference path="./typings/Misc/GetPropertyRequest.d.ts" />
/// <reference path="./typings/Misc/GetPropertySetRequest.d.ts" />
/// <reference path="./typings/Misc/GetUploadedRequest.d.ts" />
/// <reference path="./typings/Misc/GetUploadUrlRequest.d.ts" />
/// <reference path="./typings/Misc/PushRegistrationRequest.d.ts" />
/// <reference path="./typings/Misc/SocialStatusRequest.d.ts" />
/// <reference path="./typings/Multiplayer/AcceptChallengeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/ChatOnChallengeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/CreateChallengeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/DeclineChallengeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/FindChallengeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/FindMatchRequest.d.ts" />
/// <reference path="./typings/Multiplayer/FindPendingMatchesRequest.d.ts" />
/// <reference path="./typings/Multiplayer/GetChallengeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/JoinChallengeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/JoinPendingMatchRequest.d.ts" />
/// <reference path="./typings/Multiplayer/ListChallengeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/ListChallengeTypeRequest.d.ts" />
/// <reference path="./typings/Multiplayer/LogChallengeEventRequest.d.ts" />
/// <reference path="./typings/Multiplayer/MatchDetailsRequest.d.ts" />
/// <reference path="./typings/Multiplayer/MatchmakingRequest.d.ts" />
/// <reference path="./typings/Multiplayer/WithdrawChallengeRequest.d.ts" />
/// <reference path="./typings/Player Operations/AccountDetailsRequest.d.ts" />
/// <reference path="./typings/Player Operations/ChangeUserDetailsRequest.d.ts" />
/// <reference path="./typings/Player Operations/DismissMessageRequest.d.ts" />
/// <reference path="./typings/Player Operations/DismissMultipleMessagesRequest.d.ts" />
/// <reference path="./typings/Player Operations/GetMessageRequest.d.ts" />
/// <reference path="./typings/Player Operations/ListAchievementsRequest.d.ts" />
/// <reference path="./typings/Player Operations/ListGameFriendsRequest.d.ts" />
/// <reference path="./typings/Player Operations/ListInviteFriendsRequest.d.ts" />
/// <reference path="./typings/Player Operations/ListMessageDetailRequest.d.ts" />
/// <reference path="./typings/Player Operations/ListMessageRequest.d.ts" />
/// <reference path="./typings/Player Operations/ListMessageSummaryRequest.d.ts" />
/// <reference path="./typings/Player Operations/ListTransactionsRequest.d.ts" />
/// <reference path="./typings/Player Operations/LogEventRequest.d.ts" />
/// <reference path="./typings/Player Operations/SendFriendMessageRequest.d.ts" />
/// <reference path="./typings/Player Operations/SocialDisconnectRequest.d.ts" />
/// <reference path="./typings/Player Operations/UpdateMessageRequest.d.ts" />
/// <reference path="./typings/Store/AmazonBuyGoodsRequest.d.ts" />
/// <reference path="./typings/Store/BuyVirtualGoodsRequest.d.ts" />
/// <reference path="./typings/Store/ConsumeVirtualGoodRequest.d.ts" />
/// <reference path="./typings/Store/GooglePlayBuyGoodsRequest.d.ts" />
/// <reference path="./typings/Store/IOSBuyGoodsRequest.d.ts" />
/// <reference path="./typings/Store/ListVirtualGoodsRequest.d.ts" />
/// <reference path="./typings/Store/PsnBuyGoodsRequest.d.ts" />
/// <reference path="./typings/Store/SteamBuyGoodsRequest.d.ts" />
/// <reference path="./typings/Store/WindowsBuyGoodsRequest.d.ts" />
/// <reference path="./typings/Teams/CreateTeamRequest.d.ts" />
/// <reference path="./typings/Teams/DropTeamRequest.d.ts" />
/// <reference path="./typings/Teams/GetMyTeamsRequest.d.ts" />
/// <reference path="./typings/Teams/GetTeamRequest.d.ts" />
/// <reference path="./typings/Teams/JoinTeamRequest.d.ts" />
/// <reference path="./typings/Teams/LeaveTeamRequest.d.ts" />
/// <reference path="./typings/Teams/ListTeamChatRequest.d.ts" />
/// <reference path="./typings/Teams/ListTeamsRequest.d.ts" />
/// <reference path="./typings/Teams/SendTeamChatMessageRequest.d.ts" />
