/// <reference path="Cloud Data/SparkCache.d.ts" />
/// <reference path="Cloud Data/SparkDataCursor.d.ts" />
/// <reference path="Cloud Data/SparkFiles.d.ts" />
/// <reference path="Cloud Data/SparkMongoCollectionReadOnly.d.ts" />
/// <reference path="Cloud Data/SparkMongoCollectionReadWrite.d.ts" />
/// <reference path="Cloud Data/SparkMongoCursor.d.ts" />
/// <reference path="Cloud Data/SparkRedis.d.ts" />
/// <reference path="Cloud Data/SparkXmlReader.d.ts" />
/// <reference path="Configuration/SparkAchievement.d.ts" />
/// <reference path="Configuration/SparkChallengeType.d.ts" />
/// <reference path="Configuration/SparkConfig.d.ts" />
/// <reference path="Configuration/SparkCurrency.d.ts" />
/// <reference path="Configuration/SparkDownloadable.d.ts" />
/// <reference path="Configuration/SparkProperties.d.ts" />
/// <reference path="Configuration/SparkScriptOptions.d.ts" />
/// <reference path="Configuration/SparkSegmentType.d.ts" />
/// <reference path="Configuration/SparkSegmentValue.d.ts" />
/// <reference path="Configuration/SparkTeamType.d.ts" />
/// <reference path="Configuration/SparkVirtualGood.d.ts" />
/// <reference path="data/SparkDataCondition.d.ts" />
/// <reference path="data/SparkDataDeleteResult.d.ts" />
/// <reference path="data/SparkDataGetResult.d.ts" />
/// <reference path="data/SparkDataItem.d.ts" />
/// <reference path="data/SparkDataItemPersistor.d.ts" />
/// <reference path="data/SparkDataNumberOperand.d.ts" />
/// <reference path="data/SparkDataPersistResult.d.ts" />
/// <reference path="data/SparkDataQueryResult.d.ts" />
/// <reference path="data/SparkDataResult.d.ts" />
/// <reference path="data/SparkDataSortOrder.d.ts" />
/// <reference path="data/SparkDataStringOperand.d.ts" />
/// <reference path="Helper/ChatMessage.d.ts" />
/// <reference path="Integrations/SendGrid.d.ts" />
/// <reference path="Integrations/SparkHttp.d.ts" />
/// <reference path="Integrations/SparkHttpResponse.d.ts" />
/// <reference path="Leaderboards/SparkLeaderboard.d.ts" />
/// <reference path="Leaderboards/SparkLeaderboardCursor.d.ts" />
/// <reference path="Leaderboards/SparkLeaderboardEntry.d.ts" />
/// <reference path="Leaderboards/SparkLeaderboardOperations.d.ts" />
/// <reference path="Leaderboards/SparkLeaderboardPartition.d.ts" />
/// <reference path="Leaderboards/SparkLeaderboards.d.ts" />
/// <reference path="Multiplayer/PendingMatch.d.ts" />
/// <reference path="Multiplayer/SparkChallenge.d.ts" />
/// <reference path="Multiplayer/SparkMatch.d.ts" />
/// <reference path="Multiplayer/SparkMatchConfig.d.ts" />
/// <reference path="Multiplayer/SparkMatchThreshold.d.ts" />
/// <reference path="Multiplayer/SparkMultiplayer.d.ts" />
/// <reference path="Multiplayer/SparkParticipant.d.ts" />
/// <reference path="Multiplayer/SparkRealtimeServer.d.ts" />
/// <reference path="Player/SparkMessage.d.ts" />
/// <reference path="Player/SparkPlayer.d.ts" />
/// <reference path="Player/SparkPlayerExperimentSegment.d.ts" />
/// <reference path="Player/SparkPushRegistration.d.ts" />
/// <reference path="Player/SparkTeam.d.ts" />
/// <reference path="Player/SparkTeams.d.ts" />
/// <reference path="Spark.d.ts" />
/// <reference path="Spark/SparkMatchedPlayer.d.ts" />
/// <reference path="SparkGameDataService.d.ts" />
/// <reference path="Utilities/SparkBulkJob.d.ts" />
/// <reference path="Utilities/SparkBulkScheduler.d.ts" />
/// <reference path="Utilities/SparkDigest.d.ts" />
/// <reference path="Utilities/SparkLog.d.ts" />
/// <reference path="Utilities/SparkScheduler.d.ts" />
/// <reference path="Utilities/SparkUploadableUtils.d.ts" />
