/// <reference path="./typings/Cloud Data/SparkCache.d.ts" />
/// <reference path="./typings/Cloud Data/SparkDataCursor.d.ts" />
/// <reference path="./typings/Cloud Data/SparkFiles.d.ts" />
/// <reference path="./typings/Cloud Data/SparkMongoCollectionReadOnly.d.ts" />
/// <reference path="./typings/Cloud Data/SparkMongoCollectionReadWrite.d.ts" />
/// <reference path="./typings/Cloud Data/SparkMongoCursor.d.ts" />
/// <reference path="./typings/Cloud Data/SparkRedis.d.ts" />
/// <reference path="./typings/Cloud Data/SparkXmlReader.d.ts" />
/// <reference path="./typings/Configuration/SparkAchievement.d.ts" />
/// <reference path="./typings/Configuration/SparkChallengeType.d.ts" />
/// <reference path="./typings/Configuration/SparkConfig.d.ts" />
/// <reference path="./typings/Configuration/SparkCurrency.d.ts" />
/// <reference path="./typings/Configuration/SparkDownloadable.d.ts" />
/// <reference path="./typings/Configuration/SparkProperties.d.ts" />
/// <reference path="./typings/Configuration/SparkScriptOptions.d.ts" />
/// <reference path="./typings/Configuration/SparkSegmentType.d.ts" />
/// <reference path="./typings/Configuration/SparkSegmentValue.d.ts" />
/// <reference path="./typings/Configuration/SparkTeamType.d.ts" />
/// <reference path="./typings/Configuration/SparkVirtualGood.d.ts" />
/// <reference path="./typings/data/SparkDataCondition.d.ts" />
/// <reference path="./typings/data/SparkDataDeleteResult.d.ts" />
/// <reference path="./typings/data/SparkDataGetResult.d.ts" />
/// <reference path="./typings/data/SparkDataItem.d.ts" />
/// <reference path="./typings/data/SparkDataItemPersistor.d.ts" />
/// <reference path="./typings/data/SparkDataNumberOperand.d.ts" />
/// <reference path="./typings/data/SparkDataPersistResult.d.ts" />
/// <reference path="./typings/data/SparkDataQueryResult.d.ts" />
/// <reference path="./typings/data/SparkDataResult.d.ts" />
/// <reference path="./typings/data/SparkDataSortOrder.d.ts" />
/// <reference path="./typings/data/SparkDataStringOperand.d.ts" />
/// <reference path="./typings/Helper/ChatMessage.d.ts" />
/// <reference path="./typings/Integrations/SendGrid.d.ts" />
/// <reference path="./typings/Integrations/SparkHttp.d.ts" />
/// <reference path="./typings/Integrations/SparkHttpResponse.d.ts" />
/// <reference path="./typings/Leaderboards/SparkLeaderboard.d.ts" />
/// <reference path="./typings/Leaderboards/SparkLeaderboardCursor.d.ts" />
/// <reference path="./typings/Leaderboards/SparkLeaderboardEntry.d.ts" />
/// <reference path="./typings/Leaderboards/SparkLeaderboardOperations.d.ts" />
/// <reference path="./typings/Leaderboards/SparkLeaderboardPartition.d.ts" />
/// <reference path="./typings/Leaderboards/SparkLeaderboards.d.ts" />
/// <reference path="./typings/Multiplayer/PendingMatch.d.ts" />
/// <reference path="./typings/Multiplayer/SparkChallenge.d.ts" />
/// <reference path="./typings/Multiplayer/SparkMatch.d.ts" />
/// <reference path="./typings/Multiplayer/SparkMatchConfig.d.ts" />
/// <reference path="./typings/Multiplayer/SparkMatchThreshold.d.ts" />
/// <reference path="./typings/Multiplayer/SparkMultiplayer.d.ts" />
/// <reference path="./typings/Multiplayer/SparkParticipant.d.ts" />
/// <reference path="./typings/Multiplayer/SparkRealtimeServer.d.ts" />
/// <reference path="./typings/Player/SparkMessage.d.ts" />
/// <reference path="./typings/Player/SparkPlayer.d.ts" />
/// <reference path="./typings/Player/SparkPlayerExperimentSegment.d.ts" />
/// <reference path="./typings/Player/SparkPushRegistration.d.ts" />
/// <reference path="./typings/Player/SparkTeam.d.ts" />
/// <reference path="./typings/Player/SparkTeams.d.ts" />
/// <reference path="./typings/Spark.d.ts" />
/// <reference path="./typings/Spark/SparkMatchedPlayer.d.ts" />
/// <reference path="./typings/SparkGameDataService.d.ts" />
/// <reference path="./typings/Utilities/SparkBulkJob.d.ts" />
/// <reference path="./typings/Utilities/SparkBulkScheduler.d.ts" />
/// <reference path="./typings/Utilities/SparkDigest.d.ts" />
/// <reference path="./typings/Utilities/SparkLog.d.ts" />
/// <reference path="./typings/Utilities/SparkScheduler.d.ts" />
/// <reference path="./typings/Utilities/SparkUploadableUtils.d.ts" />
